### ISSUE TITLE
Update `How to run Infection only for changed files` topic

### ISSUE THREAD

**Issue by Slamdunk** [infection/site#237]
Hi, 4 years ago `How to run Infection only for changed files` [was introduced](https://github.com/infection/site/commit/27ffd049ffe0fe9e4b56509239f3af73f03384c9) in the `How-to` section, which is using the (still valid) `CHANGED_FILES=$(git diff ...)` method.

But now we have `--git-diff-filter` https://github.com/infection/site/pull/183 and `--git-diff-lines` https://github.com/infection/site/pull/228, so I think it is worth updating the main `How-to` guide to use the newer options, if I'm not missing anything.

**Comment by maks-rafalko** [comment]
Thanks for this suggestion, @Slamdunk
